# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'source/SpacePark.API/SpacePark.API.csproj'


- task: DotNetCoreCLI@2
  inputs: 
    command: test
    projects: 'Source/SpacePark.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: 'source/SpacePark.API'
    arguments: '--configuration $(buildConfiguration)'



- task: Docker@2
  inputs:
    containerRegistry: 'SpaceParkContainer4'
    repository: 'spaceparkbackend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'backend'
    publishLocation: 'Container'
