# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'source/SpacePark.FrontEnd'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: 'source/SpacePark.FrontEnd'
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/_PGBSNH19.spacepark-grupp-4-Frontend Pipeline/frontend/source/SpacePark.FrontEnd
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'frontend'