// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePark.source.Context;

namespace SpacePark.API.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    [Migration("20200929065508_AddedOnModelCreate")]
    partial class AddedOnModelCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacePark.API.Models.Parkinglot", b =>
                {
                    b.Property<int>("ParkingLotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SpaceportID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VisitorID")
                        .HasColumnType("int");

                    b.HasKey("ParkingLotID");

                    b.HasIndex("SpaceportID");

                    b.HasIndex("VisitorID");

                    b.ToTable("ParkingLots");

                    b.HasData(
                        new
                        {
                            ParkingLotID = 1,
                            SpaceportID = 1,
                            Status = 0
                        },
                        new
                        {
                            ParkingLotID = 2,
                            SpaceportID = 1,
                            Status = 0
                        },
                        new
                        {
                            ParkingLotID = 3,
                            SpaceportID = 1,
                            Status = 0
                        },
                        new
                        {
                            ParkingLotID = 4,
                            SpaceportID = 1,
                            Status = 0
                        },
                        new
                        {
                            ParkingLotID = 5,
                            SpaceportID = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("SpacePark.API.Models.Spaceport", b =>
                {
                    b.Property<int>("SpacePortID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SpacePortID");

                    b.ToTable("SpacePorts");

                    b.HasData(
                        new
                        {
                            SpacePortID = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("SpacePark.API.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorID");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("SpacePark.API.Models.Parkinglot", b =>
                {
                    b.HasOne("SpacePark.API.Models.Spaceport", "Spaceport")
                        .WithMany("Parkinglots")
                        .HasForeignKey("SpaceportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpacePark.API.Models.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorID");
                });
#pragma warning restore 612, 618
        }
    }
}
